# Generated by Django 5.1.1 on 2024-09-26 18:44
import typing

import django.db.models.deletion
from django.db import migrations, models

import wallet.validators


class Migration(migrations.Migration):
    initial = True

    dependencies: typing.ClassVar = []
    operations: typing.ClassVar = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[wallet.validators.validate_wallet_balance],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txid", models.CharField(max_length=255, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["wallet"], name="wallet_tran_wallet__4da541_idx"
                    )
                ],
            },
        ),
    ]
